# frontend/Dockerfile.dev
FROM node:20-slim

WORKDIR /app

# COPY package*.json ./
# RUN npm install -g npm@latest && npm install && npm install next@latest react@latest react-dom@latest

# COPY . .

EXPOSE 3000
#CMD porque es facilmente reemplazable via sobre escritura al llamar el contenedor 
#(Esta practica es comun en DevContainers)
CMD ["npm","run","dev"]