FROM eclipse-temurin:21-jdk

# Utilidades opcionales 
#RUN apt-get update && apt-get install -y \    
   # curl
   
WORKDIR /workspace

EXPOSE 8080

#CMD ["bash", "./gradlew bootstrap:bootRun -t"]