FROM eclipse-temurin:21-jdk

# Utilidades opcionales (inotify ayuda con algunos watchers en host)
#RUN apt-get update && apt-get install -y \    
   # curl

# Carpeta de trabajo: tu proyecto Spring Boot
WORKDIR /workspace

EXPOSE 8080

CMD ["bash", "./gradlew bootstrap:bootRun -t"]